---
title: "Missing Data Tutorial"
author: "Yichi Zhang"
date: "2023-03-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mice)
library(tidyverse)
library(naniar)
library(rio)
```

## Problems with Missingness

<!-- ```{r} -->
<!-- mean(linelist$age) -->
<!-- ``` -->

## Assess Missingness

```{r}
# import the linelist
linelist <- import("linelist_cleaned.rds")
# view the first 6 observations of the dataset
head(linelist)
# check the number of NAs in the dataset by columns
colSums(is.na(linelist))
# the dimension of the original dataset
dim(linelist)
```
### Functions to Remove Missing Values

<!-- ```{r} -->
<!-- ## listwise deletion -->
<!-- na.omit(linelist) -->
<!-- ## drops rows missing values for any of these columns -->
<!-- linelist %>%  -->
<!--   drop_na(case_id, date_onset, age)  -->
<!-- ## remove NAs by specifing the input parameters -->
<!-- mean(linelist$age, na.rm = TRUE) -->
<!-- ``` -->

```{r}
# percent of ALL data frame values that are missing
pct_miss(linelist)
# percent of rows with any value missing
pct_miss_case(linelist)
# percent of rows that are complete
pct_complete_case(linelist)
# complete.cases(linelist)
```

## Visualize Missingness

```{r}
## show the number of missing in each column
gg_miss_var(linelist, show_pct = TRUE)
## split the data by a variable
linelist %>% 
  gg_miss_var(show_pct = TRUE, facet = outcome)
```

```{r}
ggplot(
  data = linelist,
  mapping = aes(x = age_years, y = temp)) +     
  geom_miss_point()
gg_miss_fct(linelist, age_cat5)
## change over time
gg_miss_fct(linelist, date_onset)
```

```{r}
outcome_missing <- linelist %>%
    mutate(week = lubridate::floor_date(date_onset, "week")) %>%   # create new week column
    group_by(week) %>%                                             # group the rows by week
    summarise(                                                     # summarize each week
        n_obs = n(),                                                  # number of records
        
        outcome_missing = sum(is.na(outcome) | outcome == ""),        # number of records missing the value
        outcome_p_miss  = outcome_missing / n_obs,                    # proportion of records missing the value
        
        outcome_dead    = sum(outcome == "Death", na.rm=T),           # number of records as dead
        outcome_p_dead  = outcome_dead / n_obs) %>%                   # proportion of records as dead
    
    tidyr::pivot_longer(-week, names_to = "statistic") %>%         # pivot all columns except week, to long format for ggplot
    filter(stringr::str_detect(statistic, "_p_"))                  # keep only the proportion values

ggplot(data = outcome_missing)+
    geom_line(
      mapping = aes(x = week, y = value, group = statistic, color = statistic),
      size = 2,
      stat = "identity")+
    labs(title = "Weekly outcomes",
         x = "Week",
         y = "Proportion of weekly records") + 
     scale_color_discrete(
       name = "",
       labels = c("Died", "Missing outcome"))+
    scale_y_continuous(breaks = c(seq(0,1,0.1)))+
  theme_minimal()+
  theme(legend.position = "bottom")
```


## Address Missingness

### Mean Imputation

```{r}
linelist <- linelist %>%
    mutate(temp_replace_na_with_mean = replace_na(temp, mean(temp, na.rm = T)))
```

### Regression Imputation

```{r}
simple_temperature_model_fit <- lm(temp ~ fever + age_years, data = linelist)

#using our simple temperature model to predict values just for the observations where temp is missing
predictions_for_missing_temps <- predict(simple_temperature_model_fit,
                                         newdata = linelist %>% filter(is.na(temp))) 
```

```{r}
model_dataset <- linelist %>%
    select(temp, fever, age_years)  
temp_imputed <- mice(model_dataset,
                     method = "norm.predict",
                     seed = 1,
                     m = 1,
                     print = F)
```

### Multiple Imputation

```{r}
# imputing missing values for all variables in our model_dataset, and creating 10 new imputed datasets
multiple_imputation = mice(
    model_dataset,
    seed = 1,
    m = 10,
    print = FALSE) 
model_fit <- with(multiple_imputation, lm(temp ~ age_years + fever))
base::summary(mice::pool(model_fit))
```

## Exercise

```{r}
fit <- lm(Ozone ~ Wind, data = airquality)
head(na.action(fit))
naprint(na.action(fit))
colSums(is.na(airquality))
```

